### PR TITLE
partialy revert bd5c1fde

### PR DESCRIPTION
**Pull request by lbonco**
flatting field increase file size

### CODE REVIEW

**Comment by lbonco** [comment]
@amedee as mentioned on [stack echange](https://stackoverflow.com/questions/41203847/itext-flat-field-increase-file-size) I do this pull request

**Comment by Snipx** [comment]
@lbonco, Hello!
Thank you for your pull request.
I have now tested the code with the file from StackOverflow and I see that everything works fine even without your fix. The resultant file is 50 kilobytes. Can you confirm that everything works now?

Regards,
Alexey

**Comment by lbonco** [comment]
@Snip, Hello,

I'm sorry, the file that I uploaded is the wrong one, can you try [this](https://drive.google.com/open?id=0B9OKk0hk4OhzZjZuLUVhakc0TDg)?

With the new file, I get 100MB file without my patch, and 650 kilobytes with it.

Regards,
Luca

**Comment by Snipx** [comment]
Hi @lbonco,
Thanks again for the contribution. It has been added at commit https://github.com/itext/itextpdf/commit/f9b3338a60769e6a22fee127b2226c52cc605229

Regards,
Alexey

**Pull request closed without merging**
