### PR TITLE
Printing more verbose information for the image in PDF.

### PR DESCRIPTION
**Pull request by dmak**
I use `PdfContentReaderTool` class to quickly look into PDF structure. Please consider the following patch that prints also meta-information for images in PDF.

### CODE REVIEW

**Comment by trumpetinc** [comment]
I'm not an admin, but the pull is for code I originally contributed - I think that the request adds value to the tool and should be accepted.

**Comment by michaeldemey** [comment]
Hi, thanks for your PR (and patience).

We'll be looking into your code and we'll update you when we've decided to merge this or not. Given trumpetinc's approval, this will most likely get merged.
Our internal reference: RND-705

**Comment by dmak** [comment]
Any chances for this pull to get merged?

**Comment by avlemos** [comment]
Hi @dmak, 

Right now [itext/itextpdf](https://github.com/itext/itextpdf) has been deprecated in favor of [itext/itext7](https://github.com/itext/itext7), although we will continue to incorporate security fixes in [itext/itextpdf](https://github.com/itext/itextpdf) (iText5).

Could you check if the issue exists in [itext/itext7](https://github.com/itext/itext7) so we can incorporate your fix?

Thank you for contribution, it is appreciated.

**Pull request closed without merging**
