### PR TITLE
Inner operator classes should have been static

### PR DESCRIPTION
**Pull request by trumpetinc**
Hello - these inner classes should be static - otherwise they hold an unnecessary reference to the PdfContentStreamProcessor

### CODE REVIEW

**Comment by blagae** [comment]
Hi @trumpetinc ,

I can accept the first change, the inner classes definitions, without further thought. This was probably a small oversight and should obviously be fixed. I have noticed that the exact same situation occurs in iText 7, probably from not suspecting a bug when porting the code. You are welcome to create a PR for iText 7 as well if you want the credit in the git log, otherwise I'd be happy to do this myself.

The second commit touches on a much more complex problem, so I will wait to accept the entire pull request until I have been able to do some debugging/performance testing on the sample file you sent in your e-mail.

Thanks for your work !
Benoit

**Comment by trumpetinc** [comment]
Sounds good - there's no rush on the static inner class adjust (sorry - I'm relatively new to Git, and I actually intended to submit this as two different requests, but that didn't work out).  If you can take care of creating the request for iText 7, I would appreciate it.
For what it's worth, limiting the size of the font cache feels hacky to me - but short of using weak references for the cache, I couldn't come up with a better way of doing it.  As I think about it, using a WeakValuedMap for the cache would probably be ideal - I think I have an implementation of a WeakValueMap that I could dig up if you prefer to go that route.
Certainly, reducing the footprint of the font objects themselves is also a good idea - but really, making the cache use weak references is probably the best overall solution.
Cheers,
- K


----------------------- Original Message -----------------------

**Comment by amedee** [comment]
If you need help to split up the 2 commits of the pull request into 2 separate pull request, let me know. It's actually not hard to do, even with changes on the same file.

**Comment by trumpetinc** [comment]
Thanks - right now, I'll just let you guys run with this (it's really not necessary to split these apart - adding the static keyword is a "correctness" thing more than functional).  I haven't been making many commits lately (buried in my day job) - when I get more involved, if I can't figure it out, I'll definitely reach out to you!


----------------------- Original Message -----------------------

**Comment by blagae** [comment]
Hi Kevin,

I’ve looked at the file you e-mailed and it looks like a glorious mess, with almost 8000 COS objects for a single page with a few hundred glyphs. As you indicated, the problem is clearly related to all those objects being loaded and cached and not being reused.

So I was thinking: instead of just defaulting to a fixed value for a cache, why not leave users the choice whether to cache ? Essentially, there will always be a trade-off in the PDF file between using a small set of fonts repeatedly, which heavily favors caching, and creating new font objects for every chunk of text, which heavily disfavors it. The solution you just pushed provides a sensible middle ground, but what if users wish to change this at runtime ?

I was thinking about allowing the user to provide a `Map` implementation to the `PdfContentStreamProcessor`. They can then choose to limit the size of the `Map` e.g. ignoring the added fonts after a number of entries, or even to disable caching at all by writing and providing a `DummyMap` implementation.

For very adventurous users, the cache may even be dynamic e.g. based on usage frequency, recent usage, etc. It's not super-hard to write a subclass of HashMap with any of those behaviors with reasonably small effort.

Anyway this is just a basic idea, maybe you've got an entirely different plan for this. Or maybe I'm overthinking :)

Benoit

**Comment by trumpetinc** [comment]
I thought of that originally - my initial thought was to have a FontProvider interface that could be passed in, and the default implementation would do caching.
But then I realized that users don't want to have to think about this stuff.  Really, the cache is there for performance purposes, so this should be transparent to the user.  What do you think about just making the cache be a weak refernce valued cache instead?
These objects are short lived anyway - we are really just protecting ourselves against huge memory problems, so it may not even be necessary to use a sophisticated cache.  We could just wrap the font values in the map in WeakReferences.  If a few of them get garbage collected, it's not a big deal that they are left in the map...  So a self evicting cache isn't necessary.
final private Map<Integer,WeakReference<CMapAwareDocumentFont>> cachedFonts = new HashMap<Integer, WeakReference<CMapAwareDocumentFont>>();
   private CMapAwareDocumentFont getFont(PRIndirectReference ind) {       Integer n = Integer.valueOf(ind.getNumber());       WeakReference<CMapAwareDocumentFont> fontRef = cachedFonts.get(n);       CMapAwareDocumentFont font = fontRef == null ? null : fontRef.get();       if (font == null) {           font = new CMapAwareDocumentFont(ind);              cachedFonts.put(n, new WeakReference<CMapAwareDocumentFont>(font));
       }       return font;   }
 
 
Like that.  If there was a concern about the cachedFonts not evicting the key when the weak reference releases it's value, then it would need to be more complicated - but that's really not a consideration here (worst case, the map might wind up with a thousand integer keys until the content stream processor is dicarded.
What do you think about that approach?
- K


----------------------- Original Message -----------------------

**Comment by blagae** [comment]
I like it, because it likely has no negative impact on anyone's use cases, and it has similar performance to your current limited cache. I'll immediately accept a pull request where you use this code instead of a limited cache. As for the iText 7 case above, I'm willing to do this myself but then you don't get the credit in the changelogs.

It also translates well to .NET, because the same class exists there. The only difference is that `WeakReference` isn't a generic class in .NET, which only requires a class cast and some programmer discipline, because all related functionality is private/internal.

**Comment by trumpetinc** [comment]
Philippe-
I have adjusted the Pull request to use the WeakReference cache strategy.  I couldn't figure out how to split the pull request into separate parts (to get the static operator inner class change into it's own pull request), but hopefully this will get you going.
Some day, I'll learn git well enough that I can do these things without it being an adventure/learning curve!


Cheers, 
 
- Kevin 
 
Kevin Day 
trumpet 
p| 480.961.6003 x1002 
e| kevin@trumpetinc.com 
www.trumpetinc.com 
LinkedIn | Trumpet Blog | Twitter 
 


----------------------- Original Message -----------------------

**Comment by trumpetinc** [comment]
I adjusted the pull request to include a new font caching strategy (using weakreferences instead of cutting the cache off at 10 fonts).  Should work better all around.

**Pull request merged**
