### PR TITLE
Added support for TIFFs without compression tag.

### PR DESCRIPTION
**Pull request by korli**
* This default to COMPRESSION_NONE as per the spec.

### CODE REVIEW

**Comment by michaeldemey** [comment]
Hi,

This pull request looks all right to me. And it should be able to merge just fine. But do you have a test file for us so that we can include it in our test suite?

Kind regards,
Michaël.

**Comment by korli** [comment]
Hi, sadly the one test file I have isn't easily shareable because this is protected personal data. I can't help much at the moment. Original picture format seems to be DICOM, has been converted to TIFF somehow. 
Cheers,

**Comment by korli** [comment]
Hi, 
it seems the same problem was fixed in Apache Commons Imaging: https://github.com/apache/commons-imaging/commit/ed6115b320aa309100ba2edabff22f5e0c51a71b
There is also a test file: https://github.com/apache/commons-imaging/blob/ed6115b320aa309100ba2edabff22f5e0c51a71b/src/test/data/images/tiff/8/no-compression-tag.tiff?raw=true
For more information, please also see the PR https://github.com/apache/commons-imaging/pull/19
Thanks!

**Comment by Snipx** [comment]
Hi,
Thanks for your pull request!
The issue has been fixed a while ago at commit https://github.com/itext/itextpdf/commit/4c48b9314cb78e74ff7cd921b2b6804126c8e9f7

Regards,
Alexey

**Pull request closed without merging**
