### PR TITLE
Support digital signature with SM3WithSM2('国密(GuoMi)'in Chinese),whic…

### PR DESCRIPTION
**Pull request by lvtaoleo**
…h is a Digital Signature Algorithm based on ECDSA

### CODE REVIEW

**Comment by mkl-public** [comment]
In `PrivateKeySignature.java` do you really mean 

`if(encryptionAlgorithm.startsWith("EC")&&hashAlgorithm=="SM3"){`

or shouldn't that be 

`if(encryptionAlgorithm.startsWith("EC")&&hashAlgorithm.equals("SM3")){`

?

**Comment by lvtaoleo** [comment]
@mkl-public thanks for your reminding，you are right

**Comment by amedee** [comment]
Your pull request also updates the BouncyCastle dependency from 1.49 to 1.59, however iText 5 has not been tested to be compatible with this version of BouncyCastle.

**Comment by lvtaoleo** [comment]
@amedee emmm,the BouncyCastle 1.51 started supporting the SM3(the digest algorithm of GuoMi). The recent three versions 1.57-1.58 all update the part of SM2 and SM3. This commit needs return new SM3.Digest() in itext/src/main/java/com/itextpdf/text/pdf/security/BouncyCastleDigest.java

**Comment by amedee** [comment]
It has not been tested if the upgrade of the BouncyCastle dependency doesn't break anything else in iText. In the past Bouncycastle has made API breaking changes, even in minor releases, so we consider upgrading the BouncyCastle dependency a high risk change.

**Comment by lvtaoleo** [comment]
@amedee maybe, i can implement the SM3digest class

**Comment by lvtaoleo** [comment]
@amedee I have implement the SM3 Digest without upgrading the BouncyCastle dependency

**Comment by lvtaoleo** [comment]
@iText-CI

**Comment by avlemos** [comment]
Hi @lvtaoleo, 

Right now [itext/itextpdf](https://github.com/itext/itextpdf) has been deprecated in favor of [itext/itext7](https://github.com/itext/itext7), although we will continue to incorporate security fixes in [itext/itextpdf](https://github.com/itext/itextpdf) (iText5).

Could you check if the issue exists in [itext/itext7](https://github.com/itext/itext7) so we can incorporate your fix?

Thank you for contribution, it is appreciated.

**Comment by yuhai83** [comment]
@lvtaoleo, 大神你好啊 ，国密的 ，你有 编译好的jar吗 ？我这边也在研究 ，可否 分享看看啊 ，大神 。

**Pull request closed without merging**
