### PR TITLE
Some slightly malformed PDFs have PdfNull as AcroForm entry

### PR DESCRIPTION
**Pull request by trumpetinc**
We were seeing ClassCastException on the return from PdfReader.getPdfObject() in PdfStamperImpl b/c PdfNull was being returned instead of null - best to not cast at that point and do an instanceof check later.

### CODE REVIEW

**Comment by trumpetinc** [comment]
Hi all - any chance of getting this pull request accepted?

**Comment by pavel-alay** [comment]
@trumpetinc, could you attach a test file?

**Comment by trumpetinc** [comment]
Unfortunately, the file in question contained sensitive information, so I
am not able to submit the sample file that caused this request.

I suppose we could manually craft a file that has pdfnull for the acroform
entry? Will itext allow us to override that?

K

Kevin Day
trumpet
480.961.6003 x 1002
kevin@trumpetinc.com
www.trumpetinc.com

**Comment by trumpetinc** [comment]
ok - I figured out how to add a unit test without relying on the original source document.  This fails with current code, passes with the fixed code.

**Comment by michaeldemey** [comment]
@trumpetinc 
We'll go over it and merge it after the build passed on our end.

Thanks for the contribution!
Ref: RND-707

**Comment by avlemos** [comment]
Hi @trumpetinc, 

Right now [itext/itextpdf](https://github.com/itext/itextpdf) has been deprecated in favor of [itext/itext7](https://github.com/itext/itext7), although we will continue to incorporate security fixes in [itext/itextpdf](https://github.com/itext/itextpdf) (iText5).

Could you check if the issue exists in [itext/itext7](https://github.com/itext/itext7) so we can incorporate your fix?

Thank you for contribution, it is appreciated.

**Pull request closed without merging**
