### PR TITLE
Update OCSPVerifier.java

### PR DESCRIPTION
**Pull request by lvtaoleo**
The OCSPResponse of signCert is signed by issuerCert of signCert. How can you verify CertA by the publickey of CertA

### CODE REVIEW

**Comment by lvtaoleo** [comment]
@amedee

**Comment by lvtaoleo** [comment]
The issuer cert is not the self-sign cert

**Comment by mkl-public** [comment]
It is wrong to completely remove that `responderCert.verify(issuerCert.getPublicKey())` line but it clearly belongs at the end of the `if (responderCert == null) { ... }` before, i.e. it must be executed if the OCSP response is **not** signed by the _issuerCert of signCert_ but by a dedicated certificate instead.

Thus, move that `verify` call and the preceding comment up before the preceding `}`.

**Comment by lvtaoleo** [comment]
@mkl-public i know that the verify is to make sure that ocsp respond the true status of signCert , so i replace it with 
signCert.verify(responderCert.getPublicKey());

**Comment by avlemos** [comment]
Hi @lvtaoleo, 

Right now [itext/itextpdf](https://github.com/itext/itextpdf) has been deprecated in favor of [itext/itext7](https://github.com/itext/itext7), although we will continue to incorporate security fixes in [itext/itextpdf](https://github.com/itext/itextpdf) (iText5).

Could you check if the issue exists in [itext/itext7](https://github.com/itext/itext7) so we can incorporate your fix?

Thank you for contribution, it is appreciated.

**Pull request closed without merging**
