### PR TITLE
added check marker for BDC when nested in block which is to be removed

### PR DESCRIPTION
**Pull request by derlucas**
I wanted to remove some components from my PDF. We arranged stuff in layers to be able to to so, but iText missed some parts when removing Optional Content. I drew an explanation for my case.

I think the Parser is missing the BDC and therefore not incrementing the internal mc_balance variable, so when it gets to the EMC it stops rather than decrementing.

I have tested this only with two different PDF files and its working. I cannot guarantee that this fix is completely right.

### CODE REVIEW

**Comment by blagae** [comment]
Your commit looks like a sensible fix to me, but could you add your iText-related code either as a comment, or as a commit containing a test if you are willing to disclose your full use case & input file ?

This will help us to assess the issue with other files than yours, and to see whether there's anything else we might have missed.

**Comment by derlucas** [comment]
I added a test case: https://github.com/derlucas/itextpdf/commit/5cbe822d85b35b1e0d2a2fbeeebc9c81c9d79ab1
The purple Button should disappear completely but the text is still beeing visible after OCG removal. With my fix, everything is removed.

**Comment by blagae** [comment]
Hi @derlucas ,

Your pull request has been accepted into iText, even though it doesn't look like it. Apparently my merge commit created a conflict on your repository, so I can't formally accept your pull request anymore in the Github UI.

I'm not sure why this happened, but I guess it has to do with my changes to improve your test. So for the records of Github your pull request has been rejected, but your code was added to the repository under your credentials. Sorry for the hiccup, but the main goals (your code was added & you get the credit for it) are achieved, so I hope you're ok with it.

Thanks for your efforts !
Benoit

**Comment by blagae** [comment]
Hi @derlucas ,

I had to make another modification to your source code, because one of our internal tests was failing. You could obviously not foresee this, but I thought you might like to know so that you can use the newer version. The fix is in https://github.com/itext/itextpdf/commit/8b7dab0cf901d35da917b5e869977a57875f98f1

**Pull request closed without merging**
