### PR TITLE
Allow additional mappings of OID with HR algorithm names

### PR DESCRIPTION
**Pull request by nklmthr**
Allow additional mappings of OID with HR algorithm names

### CODE REVIEW

**Comment by nklmthr** [comment]
Created new Pull based on discussions in Pull Request https://github.com/itext/itextpdf/pull/36

**Comment by michaeldemey** [comment]
Thanks for the new PR!

The code looks good, but I think that throwing an Exception is overkill for trying to override existing oid's. I'd either let the user override it, at own risk of course, but this allows them to "correct" their own entries. Or I'd just return a boolean indicating success/failure of the addition.

If you want to discuss this PR with us, I sent an invitation to our slack to the e-mail address provided in your commit a few days ago.

Our internal reference: RND-725

Kind regards,
Michaël.

**Comment by amedee** [comment]
I recommend squashing the two commits (`git rebase --interactive HEAD~2`) and then force pushing your local branch. This will automatically update the pull request.

**Comment by michaeldemey** [comment]
I've just merged this PR. Thanks for the contribution. 👍

**Pull request closed without merging**
